#!/bin/sh
#insmod /root/mac80211_hwsim.ko radios=2
insmod /lib/modules/4.14.180/kernel/drivers/net/wireless/mac80211_hwsim.ko radios=1 starting_mac_addr=0
hostapd -dd -B /etc/hostapd/hostapd.conf
ifconfig hwsim0 up
ifconfig wlan0 172.16.16.1
ifconfig wlan0 up
