#!/bin/sh

if [ $# -lt 1 ]
then
    echo "Usage: $0 <machine_number>"
    exit 1
fi

case $1 in
  1) IP="192.168.224.101";;
  2) IP="192.168.224.102";;
  3) IP="192.168.224.103";;
esac

ifconfig eth0 ${IP}
echo "eth0: ${IP}"
